### ISSUE TITLE
Hiện thực API về trigger

### ISSUE THREAD

**Issue by HienLe2004** [dath-241/coin-price-be-go#4]
* Trigger Condition: - Giá Spot/Future tăng/giảm hơn 1 mốc nào đó, vào/ra range nào đó
- Mức độ chênh giá giữa spot/future so với 1 mốc nào đó, vào/ra range nào đó
- Funding rate tăng/giảm hơn 1 mốc nào đó, vào/ra range nào đó
- Funding rate Interval thay đổi
- New Symbol listing, delisting
* Snooze Condition
    - One-time
    - Once in duration
    - Repeat till n times/At Specific Time/Forever

**Comment by qkhbcxcshcmut** [comment]
### **TẠO CẢNH BÁO GIÁ**

**1. Description:**

- Endpoint:
`/api/v1/vip2/alerts (POST)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**




### **LẤY TẤT CẢ CẢNH BÁO GIÁ CỦA 1 NGƯỜI DÙNG CỤ THỂ**

**1. Description:**

- Endpoint:
`/api/v1/users/:id/alerts (GET)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**





### **LẤY TẤT CẢ CẢNH BÁO GIÁ**

**1. Description:**

- Endpoint:
`/api/v1/vip2/alerts (GET)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**




### **LẤY CẢNH BÁO GIÁ*

**1. Description:**

- Endpoint:
`/api/v1/vip2/alerts/:id (GET)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**





### **XÓA CẢNH BÁO GIÁ**

**1. Description:**

- Endpoint:
`/api/v1/vip2/alerts/:id (DELETE)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**




### **TRA CỨU NHỮNG SYMBOL ĐƯỢC THÊM MỚI HOẶC NIÊM YẾT**

**1. Description:**

- Endpoint:
`/api/v1/vip2/symbol-alerts (GET)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**





### **GỬI THÔNG BÁO VỀ CẢNH BÁO QUA EMAIL CHO NGƯỜI DÙNG**

**1. Description:**

- Endpoint:
`/api/v1/users/:id/alerts/notify (POST)`

- Request Body:  
```
{
  "email": "string"
}
```
**2. Demo:**

**Comment by qkhbcxcshcmut** [comment]
# *TRIGGER CONDITION*

### **Giá Spot/Future tăng/giảm hơn 1 mốc nào đó**

**Demo**





### **Mức độ chênh giá giữa spot/future so với 1 mốc nào đó**

**Demo**





### **Funding rate tăng/giảm hơn 1 mốc nào đó**

**Demo**




### **Funding rate Interval thay đổi**

**Demo**

**Comment by qkhbcxcshcmut** [comment]
# *SNOOZE CONDITION*

### **One-time**

**Demo**





### **Once in duration**

**Demo**





### **Repeat till n times**

**Demo**




### **Repeat at specific time**

**Demo**



### **Repeat forever**

**Demo**
