### ISSUE TITLE
Hiện thực API về authentication 

### ISSUE THREAD

**Issue by HienLe2004** [dath-241/coin-price-be-go#6]

**Comment by Sangquangnqs** [comment]
### **Title: Phát triển tính năng đăng ký tài khoản cho người dùng**

**1. Description:**

Mục tiêu: 

- Tạo tính năng đăng ký tài khoản cho người dùng trong ứng dụng, cho phép người dùng tạo tài khoản bằng cách cung cấp các thông tin cần thiết và nhận thông báo nếu quá trình đăng ký thành công hoặc xảy ra lỗi.

Yêu cầu:

- Endpoint:
`/auth/register (Phương thức POST)`

- Màn hình đăng ký:
Bao gồm các trường nhập: "Name ","Email" ,"Password" và các trường khác nếu cần (tên người dùng, số điện thoại, ngày sinh, địa chỉ, v.v.).

- Request Body:  
Chứa các trường thông tin cần thiết cho đăng ký tài khoản, cụ thể là:
```
{
  "name": "string",
  "email": "string",
  "password": "string"
}
```


- Xác thực đầu vào:
Kiểm tra xem độ dài của tên từ 1 đến 50 kí tự và chỉ gồm kí tự chữ không.
Kiểm tra email có đúng định dạng và chưa được sử dụng.
Mật khẩu phải đáp ứng yêu cầu độ dài (tối thiểu 8 ký tự) và bao gồm cả chữ,số và kí tự đặc biệt.

- Xử lý phản hồi:

**201 Created:** Nếu đăng ký thành công, trả về thông báo "User registered successfully" và user_id.
```
{
  "message": "User registered successfully",
  "user_id": "string"
}
```
**400 Bad Request:** Nếu thông tin nhập không hợp lệ (vì thiếu hoặc sai định dạng).
**409 Conflict:** Nếu email đã tồn tại trong hệ thống, hiển thị thông báo: "Email already exists.".

- Kết quả mong muốn:
Người dùng mới có thể đăng ký tài khoản thành công khi cung cấp thông tin hợp lệ.
Hệ thống trả về phản hồi thích hợp với từng trường hợp, bao gồm các thông báo lỗi nếu có.

**2. Demo Kết quả:**

- Trường hợp thành công:

Khi người dùng nhập đúng name, email, và password hợp lệ, hệ thống trả về 201 Created:
```
{
  "message": "User registered successfully",
  "user_id": "string"
}
```
Hệ thống sẽ lưu thông tin đăng ký trong database.
Lúc này tài khoản của người dùng sẽ được tạo thành công. 

- Trường hợp lỗi:

Nếu thông tin nhập vào không hợp lệ (ví dụ email sai định dạng hoặc thiếu password), trả về 400 Bad Request.
Nếu email đã tồn tại, trả về 409 Conflict với thông báo  "Email already exists."

**3. Screenshots:**

_201 Created:_
![image](https://github.com/user-attachments/assets/e367fa32-6ac7-4f52-beda-e39e3605508d)

_400 Bad Request:_
![image](https://github.com/user-attachments/assets/a7cec9a1-4ea1-412c-a306-2131d75626e8)
![image](https://github.com/user-attachments/assets/b9b9474d-01d6-4944-a780-da0662ca684d)
![image](https://github.com/user-attachments/assets/bce94498-a997-4dd1-80cf-19b9ce4cfa79)

_409 Conflict:_
![image](https://github.com/user-attachments/assets/b85c63a3-48dc-45d6-ae8a-f1612225dc61)

**4. Proposed Solution:**
- Backend:
Tạo API ` /auth/register` với phương thức `POST` để nhận thông tin đăng ký từ người dùng.
Kiểm tra tính hợp lệ của dữ liệu, xác nhận email chưa được sử dụng, và lưu thông tin người dùng vào cơ sở dữ liệu nếu hợp lệ.

- Frontend:
Tạo form đăng ký với các trường `name`, `email`, và `password`.
Hiển thị thông báo thành công hoặc lỗi tùy thuộc vào phản hồi từ API.

**Assignees**:
@tacsquang & @Sangquangnqs

**Comment by Sangquangnqs** [comment]
### **Title: Phát triển tính năng đặt lại mật khẩu qua email (Forgot Password)**

**1. Description:**

Mục tiêu: 

- Tạo tính năng cho phép người dùng đặt lại mật khẩu nếu quên, bằng cách gửi liên kết đặt lại mật khẩu qua email. Người dùng sẽ nhận được liên kết và có thể tạo mật khẩu mới cho tài khoản của họ.

Yêu cầu:

- Endpoint:
`/auth/forgot-password (Phương thức POST)`

- Request Body:  
Gửi địa chỉ email của người dùng cần đặt lại mật khẩu:
```
{
  "email": "string"
}
```


- Xác thực đầu vào:
Đảm bảo trường email không được bỏ trống.
Kiểm tra định dạng email hợp lệ (có dạng username@domain.com).
Nếu email không hợp lệ hoặc bỏ trống, trả về lỗi 400 Bad Request với thông báo rõ ràng.
Kiểm tra xem email có trong database không (nếu có thì gửi mail về cho user, còn không thì hiển thị thông báo không tìm thấy email)

- Xử lý phản hồi:

**200 OK:** Nếu email tồn tại trong hệ thống, gửi liên kết đặt lại mật khẩu thông qua email bao gồm giao diện html thông báo đặt lại mật khẩu và trả về thông báo:
```
{
  "message": "Password reset link sent to your email"
}
```
**404 Not Found:** Nếu email không tồn tại trong hệ thống, trả về lỗi `"User not found with this email"` để thông báo rằng email không hợp lệ 
**400 Bad Request:** Nếu email không hợp lệ hoặc để trống: trả về phản hồi ` "Invalid request format"`.

- Kết quả mong muốn:
Nếu người dùng nhập đúng email đã đăng ký, họ sẽ nhận được một email có liên kết đặt lại mật khẩu.
Nếu email không có trong hệ thống, trả về thông báo lỗi tương ứng mà không tiết lộ quá nhiều chi tiết vì lý do bảo mật.

**2. Demo Kết quả:**

- Trường hợp thành công (200 OK):

Khi người dùng nhập đúng địa chỉ email đã đăng ký, hệ thống gửi email với liên kết đặt lại mật khẩu, đồng thời trả về:
```
{
  "message": "Password reset link sent to your email"
}

```

- Trường hợp lỗi:

Khi người dùng nhập email không tồn tại trong hệ thống, trả về 404 Not Found.
Khi người dùng nhập email không hợp lệ hoặc để trống, trả về 400 Bad Request.

**3. Screenshots:**

_200 OK:_
![image](https://github.com/user-attachments/assets/eecbe6ad-057e-4275-a86e-bc0cb2c673b4)
![forgot_200_1](https://github.com/user-attachments/assets/69a91bd7-917b-4a85-b20b-6c9c91751b25)
Sau khi người dùng click vào button Reset Password, 1 đường link chứa token được tạo:
![image](https://github.com/user-attachments/assets/4075f1b4-8298-4c15-b2b8-7468464250e3)


_404 Not Found:_
![image](https://github.com/user-attachments/assets/c925a805-1b19-4222-81c6-21c42be6314f)

_400 Bad Request:_
![image](https://github.com/user-attachments/assets/1a580990-887d-487d-83dd-08b78e653330)
![image](https://github.com/user-attachments/assets/03404122-b9b1-47e8-94e1-6cb1f273e5da)

**4. Proposed Solution:**
- Backend:
Tạo API ` /auth/register` với phương thức `POST` để nhận email của người dùng.
Kiểm tra sự tồn tại của email trong database. Nếu có, tạo mã token và gửi liên kết đặt lại mật khẩu đến email của người dùng.

- Frontend:
Tạo form "Quên mật khẩu" với trường nhập Email.
Hiển thị thông báo thành công hoặc lỗi từ backend để người dùng nhận biết.

**Assignees**:
@tacsquang & @Sangquangnqs

**Comment by Sangquangnqs** [comment]
### **Title: Phát triển tính năng đặt lại mật khẩu (Reset Password)**

**1. Description:**

Mục tiêu: 

-  Phát triển tính năng cho phép người dùng đặt lại mật khẩu của họ thông qua một token xác thực từ liên kết reset. Tính năng này nhằm giúp người dùng có thể thay đổi mật khẩu sau khi nhận liên kết qua email.

Yêu cầu:

- Endpoint:
`/auth/reset-password (Phương thức POST)`

- Authorization:
Đảm bảo endpoint yêu cầu xác thực bằng Bearer Token (JWT).

- Request Body:  
`token`: Token reset mật khẩu.
`new_password`: Mật khẩu mới của người dùng.
```
{
  "token": "reset_token_here",
  "new_password": "string"
}
```


- Business Logic:
Kiểm tra tính hợp lệ của token.
Đảm bảo token còn hiệu lực và chính xác.
Cập nhật mật khẩu mới cho người dùng.
Xóa token reset mật khẩu sau khi hoàn thành thay đổi.

- Xác thực:
Đảm bảo mật khẩu mới thỏa mãn các quy định bảo mật.

- Xử lý phản hồi:

**200 OK:** Trả về thông báo `"Password changed successfully"` nếu mật khẩu được thay đổi thành công.
```
{
  "message": "Password changed successfully"
}
```
**401 Unauthorized:**  Trả về lỗi `"Invalid or expired token"` nếu token không hợp lệ hoặc đã hết hạn. 
**400 Bad Request:** Trả về lỗi `"Password must contain at least 8 characters, including letters, numbers, and special characters"` nếu mật khẩu mới không thỏa mãn các yêu cầu bảo mật.

- Kết quả mong muốn:
Nếu người dùng nhập đúng yêu cầu về mật khẩu mới và token được truyền vào hợp lệ thì mật khẩu sẽ được cập nhật thành công.
Nếu token không hợp lệ hoặc mật khẩu mới không thỏa mãn yêu cầu thì trả về thông báo lỗi tương ứng.

**2. Demo Kết quả:**

- Trường hợp thành công (200 OK):

Khi người dùng nhập đúng định dạng mật khẩu mới, token hợp lệ, hệ thống trả về thông báo:
```
{
  "message": "Password changed successfully"
}
```
Mật khẩu mới được cập nhật vào database và sử dụng cho đăng nhập về sau.
- Trường hợp lỗi:

Khi người dùng nhập mật khẩu sai quy định, trả về 400 Bad Request.
Khi token được truyền vào không hợp lệ hoặc hết hạn trả về 401 Unauthorized.

**3. Screenshots:**

_200 OK:_
![image](https://github.com/user-attachments/assets/220020c9-f768-4176-8fef-f3b7b647b542)
Sau khi đổi mật khẩu thành công ta có thể đăng nhập lại (login) với mật khẩu mới và sử dụng như bình thường:
![image](https://github.com/user-attachments/assets/95358412-5726-4ac7-80da-4668c9dd8762)

_401 Unauthorized:_
![image](https://github.com/user-attachments/assets/d08177dc-8eb4-4f48-b059-0e0665f4ac9d)

_400 Bad Request:_
![image](https://github.com/user-attachments/assets/614ee1fe-4094-44cd-991f-900330a01d41)


**4. Proposed Solution:**
- Backend:
Tạo API POST `/auth/reset-password` để người dùng có thể thay đổi mật khẩu mới thông qua token reset.
API nhận đầu vào là `token` (reset token từ email) và `new_password` (mật khẩu mới).
Xác thực `token` bằng cách giải mã JWT, kiểm tra tính hợp lệ và thời hạn.
Kiểm tra xem người dùng tồn tại trong cơ sở dữ liệu, sử dụng ID người dùng trong token.
Hash mật khẩu mới bằng `bcrypt` và cập nhật vào cơ sở dữ liệu.
Sau khi thay đổi mật khẩu thành công, xóa hoặc vô hiệu hóa token reset mật khẩu trong cơ sở dữ liệu.
Trả về phản hồi `200 OK` với thông báo `"Password changed successfully"` nếu thay đổi mật khẩu thành công.
Trả về các lỗi như `400 Bad Request` nếu đầu vào không hợp lệ, `401 Unauthorized` nếu token không hợp lệ, và `500 Internal Server Error` nếu có lỗi hệ thống.

- Frontend:
Tạo trang `"Đặt lại mật khẩu"` với một form nhập `new_password` và `token` (token lấy từ link trong email).
Hiển thị thông báo thành công hoặc lỗi từ backend để người dùng biết kết quả của hành động đặt lại mật khẩu.
Cung cấp một thông báo cho người dùng nếu mật khẩu không đáp ứng đủ các yêu cầu bảo mật (tối thiểu 8 ký tự, bao gồm chữ, số và ký tự đặc biệt).

**Assignees**:
@tacsquang & @Sangquangnqs

**Comment by tacsquang** [comment]
### **Title: Phát triển tính năng làm mới token (Refresh Token)**

**1. Description:**

_Mục tiêu:_
- Tạo tính năng cho phép người dùng làm mới token xác thực trước khi token hết hạn. Tính năng này giúp kéo dài thời gian đăng nhập mà không yêu cầu đăng nhập lại.

_Yêu cầu:_
- Endpoint: `/auth/refresh-token (Phương thức POST)`
- Request Header:
  - Authorization: `Bearer <Refresh Token của người dùng>`

_Xử lý yêu cầu:_
- Xác thực người dùng dựa trên token trong header. Nếu token không hợp lệ hoặc đã hết hạn, trả về lỗi 401 Unauthorized với thông báo:
```
{
  "message": "Invalid or expired refresh token"
}
```
- Nếu token hợp lệ, hệ thống sẽ tạo và trả về một JWT token mới để người dùng tiếp tục phiên đăng nhập mà không cần phải đăng nhập lại.

_Xử lý phản hồi:_
- 200 OK: Nếu làm mới token thành công, trả về token mới:
```
{
  "token": "new_jwt_token_here"
}
```
  Token cũ lúc này đã hết hạn và chỉ có token mới là hợp lệ cho các yêu cầu xác thực.

- 401 Unauthorized: Nếu token không hợp lệ hoặc hết hạn, trả về:
```
{
  "message": "Invalid token"
}
```
- Kết quả mong muốn: Sau khi thực hiện yêu cầu làm mới, người dùng nhận được một token mới có thời hạn sử dụng, đảm bảo phiên đăng nhập được duy trì liên tục.

**2. Demo Kết quả:**
- Trường hợp thành công (200 OK):
  Nếu Token hợp lệ, hệ thống sẽ tạo JWT token mới và trả về:
```
{
  "token": "new_jwt_token_here"
}
```
Token cũ lúc này đã hết hạn, chỉ token mới hợp lệ để sử dụng.

- Trường hợp lỗi:
  Nếu Token không hợp lệ hoặc đã hết hạn, trả về 401 Unauthorized với thông báo:
```
{
  "message": "Invalid token"
}
```

**3. Screenshots:**
- _200 OK:_
![Screenshot 2024-11-13 175825](https://github.com/user-attachments/assets/de9333f7-41b7-4f19-8eb5-22da44e090d5)

  _Token cũ lúc này đã hết hạn, chỉ token mới hợp lệ để sử dụng._
![Screenshot 2024-11-13 180005](https://github.com/user-attachments/assets/7d625697-6f75-4dd9-8efd-f16397264529)

- _401 Unauthorized:_
![Screenshot 2024-11-13 175843](https://github.com/user-attachments/assets/7df25846-fd96-4977-8bd5-7b7c0ebca45f)

**4. Proposed Solution:**

- Backend: 
  - Tạo `API /auth/refresh-token` với phương thức `POST`: API này sẽ tiếp nhận yêu cầu làm mới token của người dùng.
  - Xác thực Token: Kiểm tra Token trong request header để xác định tính hợp lệ và hạn sử dụng. Nếu token không hợp lệ hoặc đã hết hạn, trả về phản hồi lỗi với mã 401 Unauthorized để thông báo rằng phiên không còn hiệu lực.
  - Tạo JWT token mới: Nếu Token hợp lệ, hệ thống sẽ tạo một JWT token mới với thời hạn sử dụng được gia hạn. Token mới được ký với thông tin của người dùng (ví dụ: user_id) và các quyền hạn của họ, để sử dụng cho các yêu cầu tiếp theo.
  - Vô hiệu hóa token cũ: đưa token cũ vào blacklistToken và chỉ được xóa khỏi blacklistToken này sau khi hết hạn.
  - Trả về token mới: Trả về token mới trong phản hồi với mã 200 OK. Người dùng sẽ dùng token mới này để tiếp tục phiên đăng nhập.

- Frontend: Thêm logic tự động gọi API làm mới token trước khi token hiện tại hết hạn, giúp người dùng duy trì phiên đăng nhập mà không cần thao tác thủ công.

Assignees: 
@Sangquangnqs & @tacsquang

**Comment by Sangquangnqs** [comment]
### **Title: Phát triển API `GoogleLogin` để xác thực người dùng qua Google ID Token**

**1. Description:**

Mục tiêu: 

-  Xây dựng endpoint `/api/v1/auth/google-login` cho phép người dùng đăng nhập vào hệ thống bằng tài khoản Google.

Yêu cầu:

- Endpoint:
`POST /api/v1/auth/google-login`

- Dữ liệu đầu vào:
Token `Google ID (id_token)` được gửi dưới dạng `form-data`.
- Authorization:
Đảm bảo endpoint yêu cầu xác thực bằng Bearer Token (JWT).

- Xử lý phía backend:
Xác thực Google ID Token qua API của Google.
Kiểm tra tài khoản người dùng dựa trên email trong database.
Nếu người dùng không tồn tại, tạo mới.
Nếu tài khoản tồn tại, xác nhận trạng thái hoạt động.
Tạo JWT (Refresh Token & Access Token).
Lưu Refresh Token trong cookie với các cài đặt bảo mật.
- Xử lý phản hồi:

**200 OK:** Đăng nhập thành công, trả về JWT Access Token:
```
{
  "message": "Login successful",
  "token": "jwt_access_token"
}
```
**401 Unauthorized:**  Google ID Token không hợp lệ:
```
{
  "error": "Invalid Google ID token"
}
```
** 403 Forbidden:**  Tài khoản bị cấm:
```
{
  "error": "Your account is banned"
}
```
**2. Demo Kết quả:**

- Trường hợp thành công (200 OK):
Request:
```
POST /api/v1/auth/google-login HTTP/1.1
Content-Type: application/x-www-form-urlencoded
id_token=valid_google_id_token
```
Response:
```
{
  "message": "Login successful",
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
}
```
- Trường hợp lỗi:
Trường hợp Google ID Token không hợp lệ:
```
{
  "error": "Invalid Google ID token"
}
```
Trường hợp tài khoản bị cấm:
```
{
  "error": "Your account is banned"
}
```
**3. Screenshots:**

_200 OK:_
![image](https://github.com/user-attachments/assets/ca9881e3-19be-43f3-bfe7-709f6ecf5bca)

_401 Unauthorized:_
![image](https://github.com/user-attachments/assets/deddb5ba-481c-4519-b4d2-7e118f57912b)

**4. Proposed Solution:**
- Backend:
Xác thực Google ID Token: Sử dụng hàm utils.VerifyGoogleIDToken để xác minh Google ID Token.
Xử lý tài khoản người dùng: Lấy email từ Google ID Token.
Kiểm tra email trong database: Nếu không tồn tại, tạo tài khoản mới với thông tin từ Google ID Token.
Nếu tồn tại, kiểm tra trạng thái tài khoản (isActive).
Tạo JWT Tokens: Tạo Access Token và Refresh Token với các thông tin người dùng.
Thiết lập Refresh Token trong cookie.
Phản hồi: Trả về Access Token và thông báo thành công nếu không có lỗi.
Trả về lỗi chi tiết khi xảy ra vấn đề.
- Frontend:
Gửi yêu cầu API: Gửi Google ID Token qua form-data.
Nhận phản hồi từ backend.
Lưu Access Token: Lưu JWT Access Token để sử dụng cho các yêu cầu tiếp theo.

**Assignees**:
@tacsquang & @Sangquangnqs
