### ISSUE TITLE
Hiện thực API về Payment

### ISSUE THREAD

**Issue by HienLe2004** [dath-241/coin-price-be-go#7]

**Comment by tacsquang** [comment]
### **Title: Phát triển tính năng khởi tạo thanh toán nâng cấp VIP qua Momo (VIP Upgrade Payment)**

**1. Description:**

_Mục tiêu:_ 

- Cung cấp tính năng cho phép người dùng nâng cấp tài khoản lên các mức VIP thông qua thanh toán Momo. API này sẽ khởi tạo yêu cầu thanh toán với số tiền và mức VIP mong muốn, sau đó trả về URL thanh toán Momo để người dùng hoàn tất giao dịch.

_Yêu cầu:_

- **Endpoint:** `/api/v1/payment/vip-upgrade (Phương thức POST)`

- **Authorization:**
Bearer Token (JWT) trong header để xác thực quyền truy cập của người dùng.

- **Request Body:**
Gửi yêu cầu thanh toán với số tiền và mức VIP cần nâng cấp:
```json
{
  "amount": 100000,  // Số tiền cần thanh toán
  "vip_level": "VIP-1"  // Mức VIP muốn nâng cấp
}
```

- **Xác thực yêu cầu:**
  - Xác thực JWT token để đảm bảo người dùng có quyền thực hiện giao dịch.
  - Kiểm tra tính hợp lệ của thông tin trong body (số tiền phải là một số hợp lệ và `vip_level` phải là một trong các mức VIP hợp lệ).

- **Xử lý yêu cầu:**
  - Nếu thông tin hợp lệ, hệ thống sẽ kết nối với dịch vụ thanh toán Momo để tạo yêu cầu thanh toán.
  - Trả về URL thanh toán Momo và ID đơn hàng để người dùng có thể thực hiện giao dịch.

- **Xử lý phản hồi:**

  - **200 OK:** Nếu khởi tạo thanh toán thành công, trả về thông tin URL thanh toán và ID đơn hàng:
    ```json
    {
      "payment_url": "https://momo.vn/...",  // URL thanh toán Momo
      "order_id": "string"  // ID đơn hàng
    }
    ```

  - **400 Bad Request:** Nếu thông tin không hợp lệ, trả về lỗi với thông báo:
    ```json
    {
      "message": "Invalid request data"
    }
    ```

  - **401 Unauthorized:** Nếu JWT token không hợp lệ hoặc không có quyền truy cập, trả về lỗi với thông báo:
    ```json
    {
      "message": "Unauthorized access"
    }
    ```

**2. Demo Kết quả:**

- **Trường hợp thành công (200 OK):**
Khi người dùng gửi yêu cầu thanh toán hợp lệ, hệ thống sẽ trả về URL thanh toán Momo để người dùng hoàn tất giao dịch:
```json
{
  "payment_url": "https://momo.vn/...",
  "order_id": "string"
}
```

- **Trường hợp lỗi (400 Bad Request):**
Nếu yêu cầu không hợp lệ (ví dụ: số tiền không hợp lệ hoặc `vip_level` không đúng), trả về lỗi 400:
```json
{
  "message": "Invalid request data"
}
```

- **Trường hợp lỗi (401 Unauthorized):**
Nếu người dùng không cung cấp JWT token hợp lệ trả về lỗi 401:
```json
{
  "message": "Invalid token"
}
```

**3. Screenshots:**

- _200 OK:_
![Screenshot 2024-11-14 174308](https://github.com/user-attachments/assets/6a195cc1-6223-418c-9674-6fbec1d1e397)

  _URL Momo:_
![Screenshot 2024-11-14 174327](https://github.com/user-attachments/assets/a7c4953a-53b3-4555-9306-80109a18ca15)

- _400 Bad Request:_
_vip_level không đúng_
![Screenshot 2024-11-14 174140](https://github.com/user-attachments/assets/21e522d6-5933-4b16-ae83-ccea5e06321f)
_amount không đúng_
![Screenshot 2024-11-14 174216](https://github.com/user-attachments/assets/473daa16-13a0-42fd-a3e5-71cfc709aa6c)

- _401 Unauthorized:_
![Screenshot 2024-11-14 174655](https://github.com/user-attachments/assets/0e8e04a9-0318-489b-84da-eb94fdcc2341)


**4. Proposed Solution:**

- **Backend:**
  - **Tạo API `/api/v1/payment/vip-upgrade` với phương thức `POST`:** API này sẽ nhận yêu cầu thanh toán từ người dùng.
  - **Xác thực JWT token:** Kiểm tra JWT token trong header để đảm bảo người dùng có quyền thực hiện yêu cầu thanh toán.
  - **Xác thực dữ liệu đầu vào:** Kiểm tra tính hợp lệ của các tham số `amount` và `vip_level` trong request body.
  - **Kết nối với dịch vụ thanh toán Momo:** Tạo yêu cầu thanh toán thông qua API của Momo, truyền thông tin số tiền và cấp độ VIP người dùng muốn nâng cấp.
  - **Trả về URL thanh toán và ID đơn hàng:** Nếu giao dịch thành công, trả về URL thanh toán Momo và ID đơn hàng để người dùng có thể thực hiện thanh toán.

- **Frontend:**
  - **Tạo giao diện thanh toán:** Cung cấp một form hoặc button cho phép người dùng nâng cấp lên VIP với mức thanh toán tương ứng.
  - **Hiển thị URL thanh toán:** Sau khi nhận được phản hồi từ backend, hiển thị URL thanh toán Momo để người dùng có thể hoàn tất giao dịch.
  - **Kiểm tra và xử lý lỗi:** Hiển thị thông báo lỗi nếu có (như thông tin không hợp lệ hoặc thanh toán thất bại) để người dùng có thể thực hiện lại yêu cầu.

**Assignees:**
@Sangquangnqs & @tacsquang

**Comment by tacsquang** [comment]
### Title: Tạo API IPN cho MoMo

**Mô tả vấn đề:**
- Cần xây dựng API IPN (Instant Payment Notification) cho MoMo để nhận thông báo thanh toán ngay lập tức khi có giao dịch từ MoMo. API này sẽ nhận thông tin từ MoMo thông qua HTTP POST Request và trả về phản hồi theo yêu cầu của MoMo.

**Yêu cầu kỹ thuật:**

1. **Phương thức HTTP:**  
   - Phương thức POST.
   - URL yêu cầu được cung cấp bởi MoMo trong trường `ipnUrl`.

2. **Header yêu cầu:**
   - `Content-Type`: application/json

3. **Payload (Dữ liệu yêu cầu từ MoMo):**
   - **partnerCode** (String) - Mã tích hợp đối tác.
   - **orderId** (String) - Mã đơn hàng của đối tác.
   - **requestId** (String) - requestId của đối tác.
   - **amount** (Long) - Số tiền thanh toán.
   - **orderInfo** (String) - Thông tin đơn hàng.
   - **orderType** (String) - Loại thanh toán, giá trị mặc định là `momo_wallet`.
   - **transId** (Long) - Mã giao dịch của MoMo.
   - **resultCode** (int) - Trạng thái giao dịch của đơn hàng.
   - **message** (String) - Mô tả trạng thái giao dịch.
   - **payType** (String) - Hình thức thanh toán (web hoặc qr).
   - **responseTime** (Long) - Thời gian trả kết quả thanh toán (dạng timestamp).
   - **extraData** (String) - Thông tin thêm (Mặc định là `""`).
   - **signature** (String) - Chữ ký HMAC_SHA256 xác thực tính đúng đắn của dữ liệu.

4. **Cấu trúc Dữ liệu HMAC_SHA256 cho signature:**
   - Đảm bảo sử dụng định dạng sau khi sắp xếp các tham số từ A-Z:
     ```
     HMAC_SHA256(accessKey=$accessKey&amount=$amount&extraData=$extraData&message=$message&orderId=$orderId&orderInfo=$orderInfo&orderType=$orderType&partnerCode=$partnerCode&payType=$payType&requestId=$requestId&responseTime=$responseTime&resultCode=$resultCode&transId=$transId,secretKey)
     ```

5. **Phản hồi API (HTTP Response):**
   - **HTTP Header**: `Content-Type: application/json;charset=UTF-8`
   - **HTTP Status Code**: 200
   - **HTTP Payload**: Thông tin phản hồi từ đối tác, bao gồm:
     - **partnerCode** (String) - Mã tích hợp.
     - **requestId** (String) - Định danh request.
     - **orderId** (String) - Mã đơn hàng của đối tác.
     - **resultCode** (int) - Trạng thái xử lý giao dịch.
     - **message** (String) - Mô tả trạng thái.
     - **responseTime** (Long) - Thời gian trả kết quả (dạng timestamp).
     - **extraData** (String) - Thông tin thêm.
     - **signature** (String) - Chữ ký HMAC_SHA256.

6. **Các trạng thái giao dịch:**
   - Phản hồi trạng thái giao dịch từ MoMo, cần xử lý các mã lỗi có thể xảy ra trong quá trình thanh toán.

**Đầu ra mong muốn:**
- API IPN được xây dựng và có thể nhận thông báo từ MoMo.
- Phản hồi đúng định dạng và thông tin theo yêu cầu của MoMo.
- Hệ thống trả về mã trạng thái 200 khi nhận được yêu cầu hợp lệ từ MoMo.

**Lưu ý:**
- Kiểm tra chữ ký HMAC_SHA256 để đảm bảo tính bảo mật của dữ liệu.
- Đảm bảo rằng tất cả các tham số yêu cầu từ MoMo đều được xử lý và trả về chính xác.

**Các bước thực hiện:**
- Xây dựng endpoint API nhận thông báo từ MoMo.
- Cấu hình xử lý và xác thực chữ ký HMAC_SHA256.
- Kiểm tra tính đúng đắn của các tham số và phản hồi với mã trạng thái HTTP 200.

**Demo:**
- Endpint: `/api/v1/payment/momo-callback`

- Người dùng khởi tạo thanh toán:
![image](https://github.com/user-attachments/assets/71cd45dc-fc85-46b4-88e6-c1e1e9ff5845)

- Người dùng thanh toán:
![image](https://github.com/user-attachments/assets/daf61950-ed23-427a-b97f-71d939ef24c9)

- Sau đó MoMo sẽ điều hướng từ trang thanh toán của MoMo về trang mua hàng của mình dựa vào field redirectUrl mà ta đã truyền vào ở lệnh captureWallet và sẽ đính kèm thêm các tham số vào URL
![image](https://github.com/user-attachments/assets/65270703-3535-4849-bb01-93f596e6abf6)

- Đồng thời MoMo cũng sẽ sử dụng API được khai báo ở field ipnUrl để gửi một HTTP Request tới máy chủ đối tác.
![image](https://github.com/user-attachments/assets/4410f2fb-2abb-41da-a99d-e0bf4b2632be)

---

**Tags:**
- API
- MoMo
- IPN
- Payment Notification
- HMAC_SHA256

**Assignees:**
@Sangquangnqs & @tacsquang

**Comment by tacsquang** [comment]
### Issue: Kiểm tra trạng thái giao dịch và tra cứu thông tin giao dịch

**Mô tả vấn đề:**
- Cần xây dựng API để kiểm tra trạng thái giao dịch và tra cứu thông tin giao dịch. API này sẽ giúp các đối tác của MoMo xác minh tình trạng giao dịch (thanh toán hoặc hoàn tiền) bằng cách gửi yêu cầu kiểm tra trạng thái thông qua HTTP POST.

**Yêu cầu kỹ thuật:**

#### 1. **Phương thức HTTP:**
- **Phương thức:** POST
- **URL:** `/v2/gateway/api/query`

#### 2. **Payload (Dữ liệu yêu cầu từ đối tác):**
- **partnerCode** (String) - Mã tích hợp của đối tác (Yêu cầu).
- **requestId** (String) - Chuỗi ký tự định danh yêu cầu (Yêu cầu).
- **orderId** (String) - Mã đơn hàng thanh toán hoặc hoàn tiền cần kiểm tra trạng thái (Yêu cầu).
- **signature** (String) - Chữ ký HMAC_SHA256 được tính toán với dữ liệu sau:
  ```
  HMAC_SHA256(accessKey=$accessKey&orderId=$orderId&partnerCode=$partnerCode&requestId=$requestId,secretKey)
  ```
- **lang** (String) - Ngôn ngữ của thông điệp trả về (`vi` hoặc `en`) (Yêu cầu).

#### 3. **Cấu trúc dữ liệu yêu cầu:**
Ví dụ yêu cầu:
```json
{
    "partnerCode": "123456",
    "requestId": "1527246504579",
    "orderId": "1527246478428",
    "signature": "13be80957a5ee32107198920fa26aa85a4ca238a29f46e292e8c33dd9186142a",
    "lang": "en"
}
```

#### 4. **Cấu trúc Dữ liệu HMAC_SHA256 cho signature:**
Cần tính toán chữ ký HMAC_SHA256 dựa trên chuỗi dữ liệu:
```
HMAC_SHA256(accessKey=$accessKey&orderId=$orderId&partnerCode=$partnerCode&requestId=$requestId,secretKey)
```

---

#### 5. **Phản hồi HTTP (Response):**

- **partnerCode** (String) - Mã tích hợp của đối tác (Yêu cầu).
- **requestId** (String) - Chuỗi ký tự để định danh yêu cầu (Yêu cầu).
- **orderId** (String) - Mã đơn hàng (Yêu cầu).
- **extraData** (String) - Thông tin bổ sung từ đơn vị kinh doanh (Yêu cầu, có thể là giá trị mặc định).
- **amount** (Long) - Số tiền của đơn hàng (Yêu cầu).
- **transId** (Long) - Mã giao dịch của MoMo (Yêu cầu).
- **payType** (String) - Hình thức thanh toán (web hoặc qr) (Yêu cầu).
- **resultCode** (int) - Mã lỗi giao dịch (Yêu cầu).
- **refundTrans** (JsonArray) - Danh sách các giao dịch hoàn tiền nếu có.
- **message** (String) - Mô tả trạng thái lỗi theo ngôn ngữ yêu cầu (`vi` hoặc `en`).
- **responseTime** (Long) - Thời gian trả kết quả thanh toán về đối tác (dạng timestamp).

---

#### 6. **Cấu trúc Dữ liệu Response:**
Ví dụ phản hồi:
```json
{
    "partnerCode": "123456",
    "requestId": "1527246504579",
    "orderId": "1527246478428",
    "extraData": "",
    "amount": 1000,
    "transId": 1234567890,
    "payType": "qr",
    "resultCode": 0,
    "refundTrans": [],
    "message": "Transaction successful.",
    "responseTime": 1633504902954
}
```

#### 7. **Các bước thực hiện:**
- Cài đặt endpoint API `/v2/gateway/api/query` để nhận yêu cầu kiểm tra trạng thái giao dịch.
- Tính toán và xác thực chữ ký HMAC_SHA256.
- Xử lý các tham số và trả về phản hồi đúng định dạng.
- Đảm bảo tính bảo mật và kiểm tra các mã lỗi của giao dịch.

**Demo:**
- Tạo endpoint `/api/v1/payment/status`
- Gọi endpoint với request body là:
```
{
    "orderId": "77c9d58fb000264",
    "requestId": "77c9d58fb000264",
    "lang": "vi"
}
```
- Trả về kết quả nhận được:
![image](https://github.com/user-attachments/assets/56a8015f-9a7e-44cd-9f07-cebf0b20a657)

---

**Tags:**
- API
- MoMo
- Query Transaction
- Transaction Status

**Assignees:**
@Sangquangnqs & @tacsquang
