### ISSUE TITLE
Hiện thực websocket cho các API về giá

### ISSUE THREAD

**Issue by HienLe2004** [dath-241/coin-price-be-go#8]

**Comment by anhchienne** [comment]
**2.3 Add funding rate websocket**

- **Method**: SUBSCRIBE

- **Endpoint:** /api/v1/funding-rate/websocket

- **Description:** lấy funding rate realtime

- **Query Parameters**:

  - `symbol`: ký hiệu của cặp giao dịch (VD: BTCUSDT)

- **Message:** 
```json
{
    "eventTime": "2024-11-04 21:17:15",
    "fundingCountDown": "01:42:45",
    "fundingRate": "-0.00027098",
    "symbol": "BCHUSDT"
}
```
![image](https://github.com/user-attachments/assets/51a89579-222d-4b11-b84b-54bfc4bc2b89)
<br>
![image](https://github.com/user-attachments/assets/6c081d1f-7589-45e6-908c-cef42d63d61b)

**Comment by anhchienne** [comment]
**2.3 Add kline websocket**

- **Method**: SUBSCRIBE

- **Endpoint:** /api/v1/vip1/kline/websocket

- **Description:** lấy Kline realtime

- **Query Parameters**:

  - `symbol`: ký hiệu của cặp giao dịch (VD: BTCUSDT)

- **Message:** 
```json
{
    "baseAssetVolume": "0.04261000",
    "closeTime": "2024-11-07 09:08:06",
    "eventTime": "2024-11-07 09:08:07",
    "highPrice": "75389.32000000",
    "lowPrice": "75389.31000000",
    "openPrice": "75389.31000000",
    "quoteAssetVolume": "3212.33879260",
    "startTime": "2024-11-07 09:08:06",
    "symbol": "BTCUSDT",
    "takerBuyBaseVolume": "0.02935000",
    "takerBuyQuoteVolume": "2212.67654200"
}
```
![image](https://github.com/user-attachments/assets/c52320d3-fee8-449d-9f47-119a0239fad6)
<br>
![image](https://github.com/user-attachments/assets/5b2eb02c-d5f1-466e-8f1d-a95ee2c77238)

**Comment by HuanNguyen24** [comment]
**2.3 Add kline websocket**

- Method: SUBSCRIBE

- Endpoint: /api/v1/vip1/kline/websocket

- Description: lấy Kline realtime

- Query Parameters:

- symbol: ký hiệu của cặp giao dịch (VD: BTCUSDT)
- Message:


{
    "eventTime": "2024-11-16 18:10:39",
    "price": "91366.46000000",
    "symbol": "BTCUSDT"
}

<img width="1061" alt="image" src="https://github.com/user-attachments/assets/02728824-f331-4077-9c9f-0959b90eb903">

**Comment by HuanNguyen24** [comment]
**2.3 Add future-price websocket**

- Method: SUBSCRIBE

- Endpoint: /api/v1/future-price/websocket

- Description: lấy future-time realtime

- Query Parameters:

- symbol: ký hiệu của cặp giao dịch (VD: BTCUSDT)
- Message:


{
    "eventTime": "2024-11-16 18:15:15",
    "price": "91324.00000000",
    "symbol": "BTCUSDT"
}

<img width="1066" alt="image" src="https://github.com/user-attachments/assets/bcda30ac-8445-42ee-85d2-0d6ca0750f0f">
